
@startmindmap
* **Ética**

** Tipos de ETICA

*** Ética Nicomáquea
**** Felicidad
***** Individual
***** Colectiva
**** Razón, Virtud y Prudencia
**** Bien común

*** Ética en el Servicio Público
**** Conducta Funcionarios
**** Buena fe, Valores Morales
**** Confianza Pública
**** Compromiso Ético y Social
**** Igualdad Social y Democracia
**** Corrupción (antiético)

*** Ética Inmobiliaria
**** Principios, Valores y Normas
**** Credibilidad
**** Honestidad y Transparencia
**** Satisfacción de todas las partes
**** Bien común

*** Ética Profesional
**** Normas Éticas en el Trabajo
**** Códigos Deontológicos/Profesionales
**** Competencia y Capacidad Profesional
**** Valores Universales en el Ámbito Laboral
**** Objeción de Conciencia
***** Conflictos Éticos
**** Condiciones Éticas Profesionales
***** Competencia
***** Servicio al Cliente
***** Solidaridad

*** Ética Profesional del Docente
**** Principios Éticos en la Enseñanza
**** Libertad de Cátedra
**** Responsabilidad Social

*** Ética Profesional del Abogado
**** Principios Éticos en el Derecho
**** Justicia, Lealtad, Veracidad
**** Diligencia, Secreto Profesional

*** Ética Profesional del Administrador
**** Diligencia
**** Lealtad
**** Legalidad
**** Honestidad
**** Decoro
**** Dignidad

*** Ética Profesional del Psicólogo
**** Códigos Profesionales
**** Valores Éticos
**** Respeto a la Persona
**** Confidencialidad
**** Honestidad
**** Responsabilidad
@enduml
